### ISSUE TITLE
No latest or 1.3.1 versions available on docker hub

### ISSUE THREAD

**Issue by tagener-noisu** [MDeLuise/ytsms#1]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

I've noticed that the only version available on docker hub is 0.0.1. Is this normal? In your example compose file you have the version set to 1.3.1.

**Comment by MDeLuise** [comment]
Hi @tagener-noisu, thanks for opening the issue!

I've recently made some structural changes to the codebase and repository to enhance organization and cleanliness. As part of this cleanup effort, I change the versions of the project. I've also updated the deployment files and the readme to reflect changes, [please take a look at it](https://github.com/MDeLuise/ytsms?tab=readme-ov-file#quickstart).

Additionally, I've pushed the Docker version `0.0.1` and the `latest` versions for both the `backend` and `frontend` services.

Please let me know if you encounter any further issues or have any additional feedback.
